name: Main CI / CD Pipeline

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    uses: ./.github/workflows/build-maven.yml
    secrets: inherit 
    
  sast:
    needs: build
    name: SAST
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/SAST[CodeQL+Semgrep].yml
    secrets: inherit


  docker:
    needs: build
    permissions:
      contents: read
      packages: write
    name: Build docker image
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit


  dast:
    needs: [build,docker]
    name: DAST Scan
    uses: ./.github/workflows/DAST.yml
    secrets: inherit
    with:
      image-tag: ${{ needs.docker.outputs.image-tag }}
