name: Semgrep

on:
  workflow_dispatch:
  workflow_call:
    
permissions: 
    security-events: write
jobs:
  semgrep:
    name: semgrep/ci 
    runs-on: ubuntu-latest

    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: returntocorp/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci --sarif > semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      #- name: Upload SARIF file for GitHub Advanced Security Dashboard
       # uses: github/codeql-action/upload-sarif@v2
        #with:
         # sarif_file: semgrep.sarif
        #if: always()
     
      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v3.1.0
        if: always()
        with:
          name: semgrep.sarif
          path: ${{github.workspace}}/results.sarif
      - name: Upload analysis results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v2.1.28
        with:
          sarif_file: ${{github.workspace}}/results.sarif 
        

